name: fixing insecure modules
run-name: ${{ github.actor }} is fixing the insecure modules
on: [push]
jobs:
  fix-modules:
    runs-on: ubuntu-latest
    steps: 
      - name: Run npm audit
        run: |
           npm audit
